# Generated by Django 4.2.8 on 2023-12-11 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_emp_id_alter_employee_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.RegexValidator(message='Only Digits Allowed', regex='^[0-9]*$')]),
        ),
    ]
