# Generated by Django 4.2.8 on 2023-12-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_is_manager_alter_employee_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='employee.employeedepartment'),
        ),
    ]
