# Generated by Django 4.2.8 on 2023-12-12 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_leaving',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedepartment'),
        ),
    ]
